### ISSUE TITLE
翻譯認領串

### ISSUE THREAD

**Issue by monkenWu** [monkenWu/codeIgniter4-taiwan-User-Guide#1]
[最新認領狀況](https://github.com/monkenWu/codeIgniter4-taiwan-User-Guide/wiki/%E7%BF%BB%E8%AD%AF%E8%AA%8D%E9%A0%98%E6%B8%85%E5%96%AE)
認領翻譯請統一回覆至此。
認領格式有以下幾種：
1. 我要認領：`` intro/* ``
代表認領在 ``source/intro/`` 內的全部.rst檔。
2. 我要認領：``installation/index.rst``
代表認領單個檔案。
3. 我要認領：``installation/index.rst``、``installation/index.rst``、``installation/index.rst``
多個檔案的認領。

**Comment by monkenWu** [comment]
我要認領：``intro/*``

**Comment by monkenWu** [comment]
我要認領：``installation/*``

**Comment by neil585456525** [comment]
我要認領：`concepts/*`

**Comment by programbeginnerTW** [comment]
我要認領：helpers/*

**Comment by monkenWu** [comment]
我要認領 ``tutorial/*``

**Comment by neil585456525** [comment]
我要認領 ``incoming/*``

**Comment by monkenWu** [comment]
我要認領 ``general/*``

**Comment by s13113143** [comment]
我要認領 ``database/*``

**Comment by monkenWu** [comment]
我要認領 ``testing/*``

**Comment by eggtower** [comment]
我要認領 ``libraries/security.rst``

**Comment by monkenWu** [comment]
我要認領 ``model/*``

**Comment by monkenWu** [comment]
我要認領 ``dbmgmt/*``

**Comment by monkenWu** [comment]
我要認領 ``cli/*``

**Comment by monkenWu** [comment]
我要認領 ``extending/*``

**Comment by monkenWu** [comment]
我要認領 outgoing/*

**Comment by ping-yee** [comment]
我要認領 libraries/honeypot.rst

**Comment by ping-yee** [comment]
我要認領 libraries/encryption.rst

**Comment by programbeginnerTW** [comment]
我要認領： helpers/*
