### ISSUE TITLE
請注意詞彙的一致姓

### ISSUE THREAD

**Issue by RicherYang** [monkenWu/codeIgniter4-taiwan-User-Guide#20]
[英文版 搜尋 optimization](https://codeigniter.com/user_guide/search.html?q=optimization) 有四筆

[中文版 搜尋 優化](https://codeigniter.tw/userguide/incoming/controllers.html?highlight=%E5%84%AA%E5%8C%96) 兩筆 
[中文版 搜尋 最佳化](https://codeigniter.tw/userguide/incoming/controllers.html?highlight=%E6%9C%80%E4%BD%B3%E5%8C%96) 兩筆 

可是中文版的分開的兩個搜尋結果應該是同樣意思的東西。

延伸的另外一個題目就是，詞彙應該要選擇源至於繁體中文的 最佳化 而不是使用源至於簡體中文後繁體化的 優化(优化)

**Comment by monkenWu** [comment]
感謝你的回應。
這是翻譯上的疏漏，我們將會在下一次的翻譯審查上修正像這樣的詞彙問題。
團隊中期過後在翻譯上引入了詞彙表的方式統一大家的翻譯，在後續的翻譯中我們都優先採用 [國家教育院](http://terms.naer.edu.tw/) 的詞彙翻譯，除非是約定俗成已經有一定使用率的的譯名，比如說：``Render`` 我們採用渲染，而非算繪、彩現或算圖，也會再著墨於簡體中文程式用詞的問題。
再次感謝你的回應。

**Comment by RicherYang** [comment]
也建議可以參考 [Microsoft 語言入口網站](https://www.microsoft.com/zh-tw/language/Search) 上面的資訊。
因為那那邊查到的翻譯，會與開發上會使用到的輔助工具所使用的詞彙有比較高的一致性。
