### ISSUE TITLE
關於 翻譯詞彙對照表 的建議

### ISSUE THREAD

**Issue by RicherYang** [monkenWu/codeIgniter4-taiwan-User-Guide#21]
分類 | 英文 | 目前 | 建議改用
--|--|--|--
基本專業名詞 | token | 令牌 | 權杖
資料庫相關 | schema | 綱目 | 結構描述
資料庫相關 | rollback | 退回 | 復原
資料庫相關 | meta data | 詮釋資料 | 中繼資料
資料庫相關 | save | 保存 | 儲存
資料庫相關 | limit * | 偏移 | 限制
資料庫相關 | offset * | 限制 | 位移
資料庫相關 | Foreign Key | 外來鍵 | 外部索引鍵
資料庫相關 | primary key | 主鍵 | 主索引鍵
資料庫相關 | unique key | 唯一鍵 | 唯一索引鍵
視圖相關 | Layout | 布局 | 版面配置
視圖相關 | Layouts | 佈局 | 版面配置
視圖相關 | Localization | 本土化 | 本地化
GIT 相關 | clone | 克隆 | 複製
HTTP 相關 | responses | 響應 | 回應
擴充核心類別相關 | publish | 發布 | 發佈

標註 * 項目原本的對照表內容有誤。

以上建議改用的詞彙，絕大多數都是源至於 https://www.microsoft.com/zh-tw/language/Search 網站查詢到的結果，多數是選擇使用與 Visual Studio 或 Azure 相同的詞彙做為建議。

並沒有將所有的項目都一一確認，只是第一眼看到覺得怪怪的進行搜尋確認。

**Comment by monkenWu** [comment]
1. schema （綱目），會取用「綱目」是因為在絕大多數臺灣出版的資料庫課本以及官方的詞彙翻譯有提到這個翻譯
2. meta data （詮釋資料）關於詮釋資料我們討論了很久，最後是採用政府最常使用的「詮釋資料」作為譯名
3. Localization（本土化）當初的候選是「在地化」與「本土化」，這些都是國家教育研究院所記載的詞彙

此外，為了防止使用上的誤解， limit 與 offset 有誤的內容，會盡快修改以及修正文件中的翻譯。

非常感謝你抽空與我們提出譯名問題，我們會把  https://www.microsoft.com/zh-tw/language/Search 也做為我們的參考選項之一最佳化我們的翻譯內容。
