### ISSUE TITLE
User Guide (靜態頁面) 內容有誤

### ISSUE THREAD

**Issue by sixsckert** [monkenWu/codeIgniter4-taiwan-User-Guide#30]
Menu > 建構第一個應用程式 > 靜態頁面
本頁內容多次提到 showme() 方法，應修正為 view() 方法

**Comment by monkenWu** [comment]
你好，謝謝你的回饋。
教學內的 showme 方法是在舊版文件同步官方版本時遺漏的舊內容，我會在下一個版本中修正這個疏漏。

**Comment by sixsckert** [comment]
感謝您！

**Comment by monkenWu** [comment]
已解決。
